# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1b89dde1455b94c139a5d941df1c942"
name = "dtfta"
application_url = "https://447f-122-180-87-40.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders"

[auth]
redirect_urls = [
  "https://447f-122-180-87-40.ngrok-free.app/auth",
  "https://447f-122-180-87-40.ngrok-free.app/auth/callback",
  "https://447f-122-180-87-40.ngrok-free.app/api/auth"
]
